period : 0.05
max_steer_radians : 0.384
v_ref : 1.5 #in m/sec
k_static : 0.8 #for lookahead distance only for pure pursuit 
min_normal_distance : 0.5 #checks normal_distance from the boundary segments
max_angle_diff : 7.5 #in degrees, checks angle with boundary segments

bot:
  kp : 0.09  
  ki : 0.36 
  kd : 0.00 

eufs:
  kp: 0.4
  ki: 0.001
  kd: 0.02

length_of_car : 
  bot: 0.5 
  eufs: 1.5
pure_pursuit : True
stanley : False
get_carstate : True
t_runtime : 1000

ground_truth:
  fixed_frame: True
perc_ppc:
  fixed_frame: True
sim_slam:
  fixed_frame: False

