period : 0.05
max_steer_radians : 0.384
v_ref : 6 #in m/sec
k_static : 0.8 #for lookahead distance only for pure pursuit 
min_normal_distance : 0.5 #checks normal_distance from the boundary segments
max_angle_diff : 7.5 #in degrees, checks angle with boundary segments
kp : 0.4
ki : 0.001
kd : 0.02
length_of_car : 1.5
pure_pursuit : True
stanley : False
get_carstate : True
t_runtime : 1000

