waypoints :
  topic : "/waypoint_array"
  data_type : "MarkerArray"

stopping :
  topic : "/stopping_array"
  data_type : "MarkerArray"

cones :

  blue :
    topic : "/cones_blue_array"
    data_type : "MarkerArray"

  yellow :
    topic : "/cones_yellow_array"
    data_type : "MarkerArray"
