waypoints :
  topic : "/waypoint_array"
  data_type : "MarkerArray"

stopping :
  topic : "/stopping_array"
  data_type : "MarkerArray"

cones :

  blue :
    topic : "/cones_blue_array"
    data_type : "MarkerArray"

  yellow :
    topic : "/cones_yellow_array"
    data_type : "MarkerArray"

boundary :
  topic : "/boundary"
  data_type : "MarkerArray"

state :
  topic : "/ground_truth/state"
  data_type : "CarState"

command : 
  topic : "/cmd"
  data_type : "AckermannDriveStamped"
