PERIOD : 0.05 #20Hz
SIMULATOR_PERCEPTION : False
SLAM : False
SLAM_DISTANCE : 10
LAP_COUNT : 4
INTERPOLATION : False
PERCEPTION_DISTANCE : 15
TRACK_WIDTH : 1.5
NUMBER_OF_WAYPOINTS : 4
ANGLE_WEIGHT : 1.4
EDGE_WEIGHT : 0.4
K_PATH_WEIGHT : 10
EXPECTED_PATH_LENGTH : 1

ellipse_dimensions:
  a : 8
  b : 4

LENGTH_OF_CAR : 1.5
BEST_PATH : True
TRACK_WIDTH : 3

