bot:
  cones:
    perc_ppc:
      topic: "/ConesCartesian"
      data_type: "Track"
    slam_ppc:
      topic: "/slam_data"


eufs:
  cones:
    sim_slam :
      topic: "/ground_truth/track"
      data_type: "ConeArrayWithCovariance"
    ground_truth :
      topic: "/ground_truth/cones"
      data_type: "ConeArrayWithCovariance"
    sim_perception :
      topic: "/perception/cones"
      data_type: "Track"
    slam : 
      topic: "/slam_data"
      data_type : "Slam_state"
  car_state:
    sim_slam : 
      topic: "/ground_truth/state"
    ground_truth :
      topic: "/ground_truth/state"
    sim_perception :
      topic: "/ground_truth/state"


publisher:
  waypoints:
    topic: "/WaypointArray"
    data_type : "PointArray"
  cones :
    blue :
      topic : "/cones_blue_array"
      data_type: "Track"
    yellow :
      topic : "/cones_yellow_array"
      data_type: "Track"